<template>
  <div class="basic-button-list">
    <bk-button loading />
    <bk-button
      class="ml10"
      theme="primary"
      loading
    />
    <bk-button
      class="ml10"
      theme="success"
      loading
    />
    <bk-button
      class="ml10"
      theme="warning"
      loading
    />
    <bk-button
      class="ml10"
      theme="danger"
      loading
    />
    <bk-button
      class="ml10"
      loading-mode="spin"
      theme="danger"
      loading
    />
  </div>
</template>
